"""empty message

Revision ID: d1b987e315f5
Revises: 81bee4c41414
Create Date: 2025-12-05 04:46:00.705314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b987e315f5'
down_revision = '81bee4c41414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Tabla Character (Esto está bien)
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('specie',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # 2. Tabla Planet (AQUÍ ESTABA EL ERROR)
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrain', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('population', sa.String(length=100), nullable=True))
        
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # 3. Tabla User (PRECAUCIÓN)
    # He cambiado nullable=False a nullable=True para evitar errores 
    # si ya tienes usuarios antiguos sin nombre en la base de datos.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True)) 
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('subscription_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscription_date')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_column('population')
        batch_op.drop_column('terrain')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('specie',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
